server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://shift_db:5432/shift_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://root:root@shift_db:5432/shift_db
    locations: classpath:db/migration

